name: commonroad-py39-rl-backup2803
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=py39h06a4308_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=py_0
  - attr=2.5.1=h166bdaf_1
  - blas=1.0=openblas
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cached-property=1.5.2=py_0
  - certifi=2025.1.31=py39h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - cuda-crt-tools=12.8.93=ha770c72_1
  - cuda-cudart=12.8.90=h5888daf_1
  - cuda-cudart_linux-64=12.8.90=h3f2d84a_1
  - cuda-cupti=12.8.90=hbd13f7d_0
  - cuda-nvcc-tools=12.8.93=he02047a_1
  - cuda-nvrtc=12.8.93=h5888daf_1
  - cuda-nvtx=12.8.90=hbd13f7d_0
  - cuda-nvvm-tools=12.8.93=he02047a_1
  - cuda-version=12.8=h5d125a7_3
  - cudnn=9.8.0.87=h81d5506_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.13=py39hf88036b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.3.9=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - flatbuffers=24.12.23=h8f4948b_0
  - fonttools=4.56.0=py39h9399b63_0
  - freetype=2.13.3=h48d6fc4_0
  - gast=0.5.3=pyhd3eb1b0_0
  - giflib=5.2.2=h5eee18b_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - gym-notices=0.0.8=pyhd8ed1ab_1
  - h5py=3.13.0=nompi_py39h30a5a8d_100
  - hdf5=1.14.3=nompi_h2d575fe_109
  - icu=75.1=he02047a_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_metadata=8.6.1=hd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - ipywidgets=8.1.5=py39h06a4308_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyterlab_widgets=3.0.13=py39h06a4308_0
  - keras=3.6.0=py39h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h6a678d5_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=16_linux64_openblas
  - libcublas=12.8.4.1=h9ab20c4_1
  - libcufft=11.3.3.83=h5888daf_1
  - libcurand=10.3.9.90=h9ab20c4_1
  - libcurl=8.12.1=h332b0f4_0
  - libcusolver=11.7.3.90=h9ab20c4_1
  - libcusparse=12.5.8.93=hbd13f7d_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=h7f8727e_1
  - libfabric=2.0.0=ha770c72_1
  - libfabric1=2.0.0=h14e6f36_1
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libgpg-error=1.51=hbd13f7d_1
  - libgrpc=1.67.1=h25350d4_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.0.3=h5eee18b_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.8.93=h5888daf_1
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.47=h943b412_0
  - libprotobuf=5.28.3=h6128344_1
  - libre2-11=2024.07.02=hbbce691_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.1=hee588c1_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=257.4=h4e0b6ca_1
  - libtiff=4.7.0=hd9ff511_3
  - libudev1=257.4=hbe16f8c_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.6=h8d12d68_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py39h5eee18b_0
  - matplotlib-base=3.9.4=py39h16632d1_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ml_dtypes=0.4.0=py39h3b40f6f_2
  - mpi=1.0.1=mpich
  - mpi4py=3.1.3=py39h32b9844_3
  - mpich=4.3.0=h1a8bee6_100
  - multiprocess=0.70.17=py39h8cd3c5a_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - namex=0.0.7=py39h06a4308_0
  - nccl=2.26.2.1=ha44e49d_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.0.1=py39heeff2f4_1
  - numpy-base=2.0.1=py39h8a23956_1
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.4.1=h7b32b05_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.14.1=py39hdb19cb5_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h3b40f6f_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pathos=0.3.3=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py39h15c0740_0
  - pip=25.0.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pox=0.3.5=pyhd8ed1ab_1
  - ppft=1.7.6.9=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.21=h9c0c6dc_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-flatbuffers=24.3.25=py39h06a4308_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=5_cp39
  - pyzmq=26.3.0=py39h4e4fb57_0
  - qhull=2020.2=h434a139_5
  - rdma-core=56.0=h5888daf_0
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=py39h06a4308_1
  - rich=13.9.4=py39h06a4308_0
  - salib=1.5.1=pyhd8ed1ab_2
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=75.8.2=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.49.1=h9eae976_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tensorflow=2.18.0=cuda126py39hdc27005_200
  - tensorflow-base=2.18.0=cuda126py39h7b6b450_200
  - tensorflow-estimator=2.18.0=cuda126py39h88c3955_200
  - termcolor=2.1.0=py39h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py39h8cd3c5a_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - ucx=1.18.0=h8887438_2
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - urllib3=2.3.0=py39h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - werkzeug=3.1.3=py39h06a4308_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.13=py39h06a4308_0
  - wrapt=1.17.0=py39h5eee18b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_1
  - pip:
      - aenum==3.1.15
      - alabaster==0.7.16
      - ale-py==0.10.2
      - alembic==1.15.1
      - antlr4-python3-runtime==4.9.3
      - babel==2.17.0
      - botorch==0.9.5
      - charset-normalizer==3.4.1
      - clarabel==0.10.0
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - commonroad-clcs==2025.1.1
      - commonroad-drivability-checker==2025.1
      - commonroad-io==2024.3
      - commonroad-reach==2025.1.0
      - commonroad-reactive-planner==2025.1
      - commonroad-route-planner==2022.3
      - commonroad-vehicle-models==3.0.2
      - cvxpy==1.6.3
      - cython==3.0.12
      - docutils==0.21.2
      - ecos==2.0.14
      - farama-notifications==0.0.4
      - filelock==3.18.0
      - fsspec==2025.3.0
      - gpytorch==1.11
      - greenlet==3.1.1
      - grpcio==1.71.0
      - gym==0.25.2
      - gymnasium==1.0.0
      - idna==3.10
      - imageio==2.37.0
      - imagesize==1.4.1
      - iniconfig==2.0.0
      - iso3166==2.1.1
      - jaxtyping==0.2.36
      - jinja2==3.1.6
      - joblib==1.4.2
      - linear-operator==0.5.1
      - lxml==5.3.1
      - mako==1.3.9
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - methodtools==0.4.7
      - mosek==11.0.12
      - mpmath==1.3.0
      - multipledispatch==1.0.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optuna==4.2.1
      - optuna-integration==4.2.1
      - osqp==0.6.7.post3
      - pbr==6.1.1
      - pluggy==1.5.0
      - pockets==0.9.1
      - polygon3==3.0.9.1
      - protobuf==3.20.2
      - pygame==2.1.0
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytest==8.3.5
      - pytz==2025.1
      - pyyaml==6.0.2
      - qdldl==0.1.7.post5
      - rtree==1.4.0
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - sb3-contrib==2.5.0
      - scikit-learn==1.6.1
      - scs==3.2.7.post2
      - seaborn==0.13.2
      - shapely==2.0.7
      - snowballstemmer==2.2.0
      - sphinx==7.4.7
      - sphinx-autodoc-typehints==2.3.0
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-apidoc==0.5.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-napoleon==0.7
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.39
      - stable-baselines3==2.5.0
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tomli==2.2.1
      - torch==2.6.0
      - tqdm==4.67.1
      - triangle==20250106
      - triton==3.2.0
      - typeguard==2.13.3
      - tzdata==2025.1
      - wirerope==1.0.0
prefix: /home/shuaiyi/Downloads/ENTER/envs/commonroad-py39-rl-backup2803
